### ISSUE TITLE
Fix CI build and optimise test process

### ISSUE THREAD

**Issue by sandjelkovic** [AxonFramework/extension-kafka#108]
### Enhancement Description

Fix the CI build by either making test more resilient to random failures, or using another approach for integration testing. 
One different approach to integration testing might be to replace `EmbeddedKafka` with `TestContainers` Kafka module.

### Current Behaviour

Since moving to GitHub Actions, the CI build and tests are not very stable. While locally all tests are green, on GHA various random tests fail on each build. Occasionally `java.lang.OutOfMemoryError: Java heap space` or similar errors will occur which may indicate the root problem for other failing tests cases and explain why there are no failures locally. It seems that the test executing process can take more than 4GB of RAM at one point which can put a lot of memory pressure on the CI JVM.

### Wanted Behaviour

Consistent CI builds and passing tests

**Comment by azzazzel** [comment]
The error I experienced while running the actions was
```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedKafka': Invocation of init method failed; nested exception is kafka.zookeeper.ZooKeeperClientExpiredException: Session expired either before or while waiting for connection
Caused by: kafka.zookeeper.ZooKeeperClientExpiredException: Session expired either before or while waiting for connection
```

So I tried (a shot in the dark) to increase the `zkSessionTimeout` value of `@EmbeddedKafka` but it didn't help. The tests were just hanging there (for over 40 min on my fork).

A also tried to run them locally with [`act`](https://github.com/nektos/act). Unfortunately I run into [this issue](https://github.com/nektos/act/issues/507). As soon as I have some time I'll try to create an action without matrix that can be run locally. Hopefully that will help debug what is going on during execution.
