### ISSUE TITLE
Error running example: "The XStream instance is a hard requirement and should be provided"

### ISSUE THREAD

**Issue by rhubarb** [AxonFramework/extension-kafka#213]
### Basic information

* Axon Framework version: 4.6.0-SNAPSHOT
* JDK version:  11
* Kafka Extension version: 4.6.0-SNAPSHOT
* Complete executable reproducer if available (e.g. GitHub Repo):

### Steps to reproduce

Simply follow the steps in the README for the kafka-extension example

### Expected behaviour

It runs at least!

### Actual behaviour

Fails at startup with:
``` 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaPublisher' defined in class path resource [org/axonframework/extensions/kafka/autoconfig/KafkaAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.axonframework.extensions.kafka.eventhandling.producer.KafkaPublisher]: Factory method 'kafkaPublisher' threw exception; nested exception is org.axonframework.common.AxonConfigurationException: The XStream instance is a hard requirement and should be provided
```
Seems related to this discussion:
https://discuss.axoniq.io/t/kafka-extension-kafka-publisher-does-not-support-axon-framework-4-5-5/3773

Without this, my first attempt at Axon framework with Kafka is dead in the water

**Comment by smcvb** [comment]
Thanks for bringing additional attention to this. We spotted it too and heard a contributor wanted to provide a fix.
As a matter of fact, that fix is present, and you can find it [here](https://github.com/AxonFramework/extension-kafka/pull/214).
