### ISSUE TITLE
Reduce unique consumer group creation when consuming events with Streamable Message Source

### ISSUE THREAD

**Issue by aupodogov** [AxonFramework/extension-kafka#273]
### Enhancement Description

When consuming events from Kafka using `StreamableKafkaMessageSource` a new consumer group id is generated each time the event stream is opened. It eventually creates too many consumer groups in Kafka, that never be used again.

### Current Behaviour

Each time when Kafka event stream opened via `StreamableKafkaMessageSource` new consumer group id suffix is generated.

### Wanted Behaviour

KafkaTrackingToken stores previously generated group id suffix and reuse it. When opening Kafka event stream with empty token (or token without group id suffix value) new group id suffix is generated and gets stored in the token.

### Possible Workarounds

Consume events with `SubscribableKafkaMessageSource` instead of `StreamableKafkaMessageSource`.

**Comment by gklijs** [comment]
Hi Podogov,

Thanks for cresting the issue. It's sonething I noticed earlier, but didn't get to to create an issue yet. Feel free to create a pull request. I'll probably be able to work on it myself otherwise in about a week.

**Comment by gklijs** [comment]
If you need to you already could configure the `groupIdSuffixFactory` on the `StreamableKafkaMessageSource.Builder` to be always the same. You do have to watch out, I think, with multiple instances. One could claim the token, but if it's part of a group, it might not claim the related partitions via the Kafka API, causing errors.

**Comment by aupodogov** [comment]
Hi @gklijs! Thanks for the advice! We decided to switch to `SubscribableMessageSource`.
I think I can provide PR for this issue next week.

**Comment by gklijs** [comment]
I took a good look, and we can do without the consumer group. We do need to check how many partitions there are the first time, after that we can rely on the token. looks like I good improvement over the current implementation.

**Comment by aupodogov** [comment]
I didn't understand, @gklijs. Could you explain your idea in more details?

**Comment by gklijs** [comment]
The functionality of storing the offsets is already not used. But to use `.subscribe(topics)` you also need an user group. However we can fetch the metadata, find the partitions, and use the `.assign(partion)` and thus skipping the need for an user group. That does require some code changes, but it will be fully compatible with the current tokens.

**Comment by gklijs** [comment]
@aupodogov fix is available with either `4.5.4-SNAPSHOT` or `4.6.0-SNAPSHOT`, please let us know if a 4.5.4 release soon would be preferable.  Thanks again for raising the issue.

**Comment by aupodogov** [comment]
@gklijs I’d rather see it in earlier release. So I vote for 4.5.4. And thanks for resolving this issue!

**Comment by gklijs** [comment]
@aupodogov there is one other fix, https://github.com/AxonFramework/extension-kafka/issues/276 we would like to include. I just opened the pr, hopefully, we can release 4.5.4 soon.

**Comment by gklijs** [comment]
@aupodogov, thanks to @smcvb, 4.5.4 is available now.
