### ISSUE TITLE
Current documentation is confusing / wrong

### ISSUE THREAD

**Issue by zambrovski** [AxonFramework/extension-kafka#304]
Hi guys,

I'm studying the changes you introduced in 4.5.4 and trying to understand how to deal with the fact that no group id is provided anymore. By doing so, I was looking through the docs and found the old description in it: https://docs.axoniq.io/reference-guide/extensions/kafka#consuming-events-with-a-streamable-message-source

I think this is very confusing:

```
The distinct group id is derived by the StreamableKafkaMessageSource through a groupIdPrefix and a groupdIdSuffixFactory, which are adjustable through the source's builder.
```
which contradicts with the changes introduced in #273 

Cheers,

Simon

**Comment by gklijs** [comment]
Hi Simon, thanks for bringing this to our attention. As the reference guide has its own repo, I created an issue referring to this one there. I think I can think it up shortly as it's not much work, and helps prevent confusion.
