### ISSUE TITLE
On Multiple Executions SubscribeableMessageSource fails to be created for the Producer

### ISSUE THREAD

**Issue by mishkaechoes** [AxonFramework/extension-kafka#32]
The reason for this appears to be due to an entry in the token_entry table. Even though we are configured for a subscribeable producer and consumer.

The second run of the application fails due to the entry in the token_entry.

Attached is a startup log that may be useful with Aspects
[ess_logs.log](https://github.com/AxonFramework/extension-kafka/files/4041706/ess_logs.log)

**Comment by mishkaechoes** [comment]
We are running RC3

**Comment by smcvb** [comment]
Thanks for filing this issue with us @mishkaechoes.

Would you be able to share how you have configured subscribable production and consumption with the Kafka Extension?
Maybe something obvious pops up from that.
Per reference, [this](https://docs.axoniq.io/reference-guide/v/4.0/extensions/kafka) is how the extension configuration is documented at the moment.

Added, I am not overly confident that your log shows the fact that the `token_entry` table blocks start up of a `SubscribeableKafkaMessageSource`. Would you mind pinpointing me to the exact location whereon you base this statement?

Lastly, would you state it's the _entire_ `token_entry` table which causes the problem or a specific entry in said table?

**Comment by mishkaechoes** [comment]
This issue is the result of a TrackingSubscriber being created by Axon despite subscribing producer being configured. The core of the issue is #33 

To answer your question it's tokenId being being non-null on the second run. The reason for this is the mismatch between globalIndex on the last saved token_entry record is higher than the current index.

**Comment by smcvb** [comment]
I will close this issue as "obsolete," as "the core of the issue" is #33, which was just closed as resolved.
