### ISSUE TITLE
Messages Replayed without a trigger resulting in a unique constraint violation domain_event_entry

### ISSUE THREAD

**Issue by mishkaechoes** [AxonFramework/extension-kafka#35]
We've encountered this problem prior to updating to RC3.

An event was fired at 8:30 am est
<img width="1669" alt="Screen Shot 2020-01-16 at 12 34 06 PM" src="https://user-images.githubusercontent.com/1927197/72548577-f6623780-385c-11ea-9b24-9b48010713ba.png">
This event was only fired once and processed by Kafka once.
Note the epoch time 1579181440697 is 8:30 am est

We observe the unique constraint violation at 10:12 am est
<img width="1394" alt="Screen Shot 2020-01-16 at 12 34 26 PM" src="https://user-images.githubusercontent.com/1927197/72548672-290c3000-385d-11ea-9104-6884e3acf538.png">

When we check the logs for how many times this event handler was triggered we discover the uninvoked rehandling of the event.

<img width="1389" alt="Screen Shot 2020-01-16 at 12 33 33 PM" src="https://user-images.githubusercontent.com/1927197/72548748-51942a00-385d-11ea-9b86-54d56c9a1519.png">

**Comment by smcvb** [comment]
Could you share a small sample project so that I can replay this exact behavior? Without such a tool we would be searching for a needle in a haystack, which is a tremendous waste of time.

Additionally, you make it sound like you are reading an event from a Kafka topic through the extension and storing it in the Event Store. Why are you doing this exactly? You can just use the Kafka topic as the event source for this service, why does it need to store them _again_ at the receiving end? Sounds slightly unnecessary on face value.

**Comment by mishkaechoes** [comment]
The problem reproduced again in a new environment that has been untouched for 4 days. We have not been able to attribute the issue to network, kafka rebalances or other user activity. If we could effectively reproduce the issue ourselves we would work towards resolving it. What is clear is that the framework is reprocessing a message that was not invoked through Kafka.

With all due respect while the project is "complicated" there have been numerous offers to use it to improve the framework by combining our mutual expertise. At this point we are evaluating how long it will take to strip it from the project. We have missed numerous deadlines due to the complexity and bugs found in the framework.

**Comment by smcvb** [comment]
> With all due respect while the project is "complicated" there have been numerous offers to use it to improve the framework by combining our mutual expertise. At this point we are evaluating how long it will take to strip it from the project. We have missed numerous deadlines due to the complexity and bugs found in the framework.

Do hope you have succeeded with adapting your code or constructing something new. 
As it stands, there are several users of this extension not mentioning any of the problems you described; hence why a sample project from your hand, present on GitHub with an explanation of how to run it, would've been beneficial for us and others, but even more so for _you and your team_.

As we haven't heard from you for the last year, I am guessing my assumption is correct in that a "solution" was found on your end.
Given that stance and the fact the problem didn't occur for anybody else yet, I will be closing this issue.

If anybody else does experience the problem, feel free to comment here.
