### ISSUE TITLE
Multiple TEP not working

### ISSUE THREAD

**Issue by pms-github** [AxonFramework/extension-kafka#37]
Got 2 aggrigate, 1 saga and 2 projections with TEP. However at run time it publushed event to either  one of the TEP (Saga / projection 1 / projection2)

Got below setup

- Kafka extension with Postgres as ES

- Order agrigate and command service

- Shipment as aggrigate and Saga event hander

- query app as event cosumer 

- Notification app event consumer

Refer source code at - https://gitlab.com/bm-cqrs/axon-kafka-distrbuted.git

**Comment by smcvb** [comment]
Given the current description it is unclear to me whether this is a "misconfiguration" or a bug, although I am guessing it is something with the set up. As such, the label "question" will be added this issue.

Additionally, I will close of this issue immediately, as the GitHub issue tracker **is not** intended for usage questions of the products. For that, I'd like to refer to StackOverflow or the [Usergroup](https://groups.google.com/forum/#!forum/axonframework).

Feel free to expand under this issue with a more thorough sample of how you are configuring your application. If I can spot it in a glance, that would help tremendously of course.
