### ISSUE TITLE
Expose Kafka subscribe(Pattern) via the SubscribableKafkaMessageSource.Builder interface

### ISSUE THREAD

**Issue by bkornmeierpax8** [AxonFramework/extension-kafka#422]
### Feature Description

Allow for `SubscribableKafkaMessageSource` to accept a `Pattern` onwhich to subscribe to Kafka messages.
Currently, when building a new `SubscribableKafkaMessageSource` we can only supply a List<String> of topics that the MessageSource' Consumer can subscribe to.
```kotlin
val source = SubscribableKafkaMessageSource.builder<String, String>()
  .topics(listOf("topic-1", "topic-2")
  ...
  .build()  
```

It would be nice to also have the ability to use a pattern instead, so that we could handle replicated topics or new topics that haven't been created yet, something like the following:
```kotlin
val source = SubscribableKafkaMessageSource.builder<String, String>()
  .topicPattern("topic-[0-9]+")
  ...
  .build()  
```

### Current Behaviour

We only allow for a fixed list of topics to be used with the builder

### Wanted Behaviour

We allow the fixed list, and the ability to use a regex pattern to subscribe to topics not yet created.

### Possible Workarounds

I am not aware of any at the moment.

## PR for possible acceptance 

I have forked the repo, and added a potential change that gets me the functionality requested:
https://github.com/AxonFramework/extension-kafka/pull/423
Would this be of interest to the community?

Thank you

**Comment by jhollanderpax8** [comment]
This is a much needed addition.  Without this it is difficult to use kafka in many of the ways it is meant to be used.  Thanks!

**Comment by smcvb** [comment]
Awesome, I wasn't aware the `Consumer` allowed `Pattern` instances too.
Lovely idea and thinks for the pull request, @bkornmeierpax8!
I do have a couple of pointers we need to cover before it's ready to merge.

In addition, I am wondering why this would only be beneficial for the `SubscribableKafkaMessageSource`.
Wouldn't the `StreamableKafkaMessageSource` benefit from this adjustment too?
