### ISSUE TITLE
Axon-spring-boot-starter - kafka version problem

### ISSUE THREAD

**Issue by marinkobabic** [AxonFramework/extension-kafka#6]
Have tried to run this two versions

- axon-spring-boot-starter version: '4.1.2'
- axon-kafka version: '4.0-M2'

but I'm getting always the binary incompatibility issue when the configuration org.axonframework.config.EventProcessingModule is getting loaded. The exception is IncompatibleClassChangeError Implementing class. I tried also to run the axon-spring-boot-starter version: '4.0' with no success.

**Comment by smcvb** [comment]
We try to aim for an equal release cadence for the framework, server and all the extensions.
Thus, a Axon Framework 4.0 works with all the 4.0 extensions release too.
The extensions to this end rely on frameworks 4.0 release too.

That means that a project which depends on 4.1 but has an extension on 4.0 will also pull in framework 4.0, which is causing the issue you're seeing here.
To resolve this we'll have to get the Kafka Extension out of its milestone. 
As pointed out under #1 yesterday, this effort will take place after we've finalized 4.2 of Framework and Server.

We will correctly update this ticket as soon as work is underway.
Lastly, thanks for marking this issue with us @marinkobabic.

**Comment by smcvb** [comment]
Updated this issue to release 4.5, as we've decided to release the Kafka Extension based on the current Framework version.
