### ISSUE TITLE
DefaultProducerFactory closes non-transactional Kafka Producer after `producerCacheSize` messages were sent

### ISSUE THREAD

**Issue by lbilger** [AxonFramework/extension-kafka#8]
We are using axon-kafka with spring boot, mostly keeping the default settings. We noticed that after sending a couple of events to kafka, the producer is closed and we get an INFO message saying `Closing the Kafka producer with timeoutMillis = 30000 ms.`

After that, sending any more events fails with `java.lang.IllegalStateException: Cannot perform operation after producer has been closed`.

Looking at the code, it seems there is a bug in `DefaultProducerFactory`. When `close` is called on the `CloseLazyProducer`, it offers itself to the `cache` queue but producers are only removed from that queue in transactional mode. Once the queue is full, the single producer is closed but still returned by subsequent calls to `createProducer`.

**Comment by smcvb** [comment]
Thanks for filing this concern with us @lbilger. 

At the moment, the Axon Kafka Extension is in a milestone state.
As such, bugs/issues like this are to be expected to some extent.

We are on the verge of pulling it out of this state in to a dedicated release though.
This concern might thus be addressed pretty soon.
However, if the resolution is pressing for your development, a contribution in the form of a pull request would definitely speed up things.

If you prefer to leave the fix to our hands, than that's obviously also fine.

**Comment by lbilger** [comment]
Thanks for the quick reply @smcvb! I have created a pull request that should fix this issue.
