### ISSUE TITLE
Subscribing Producer Mode not working as expected

### ISSUE THREAD

**Issue by muammeryucel** [AxonFramework/extension-kafka#84]
### Basic information

* Axon Framework version: 4.0.4
* JDK version: 11
* Kafka Extension version: 4.0-RC3

Kafka event publishing is supposed to work in two modes: subscribing or tracking. In tracking mode, event publishing is handled by a separate tracking event processor thread asynchronously. In subscribing mode, which is default, it should be handled within the same thread synchronously but it doesn't work as expected.

### Steps to reproduce

1. Open axon-kafka-example project in your IDE. 
2. Add a breakpoint to KafkaEventPublisher's handle method (line:77). 
3. Run the application with debug mode. 
4. When the execution hits the breakpoint, look at the stacktrace. 
5. You will see that, it is invoked by a tracking event processor asysnchronously. 

### Expected behaviour

Kafka event publishing should be invoked synchronously.

### Actual behaviour

It is invoked by a tracking event processor thread asynchronously. Subscribing mode doesn't work.

**Comment by muammeryucel** [comment]
I created a PR (https://github.com/AxonFramework/extension-kafka/pull/85) and added an integration test for this bug.

To solve this bug, I assigned handler instance matching for default kafka processing group. I am not sure if this is a proper solution, but when I investigated deeply, I noticed that, if there is not any assignment for a handler instance, the framework looks for @ProcessingGroup annotation on the handler's class. If the annotation doesn't exist, it uses package name as the processing group name. Since processing group names don't match with each other, instead of creating subscribing implementation, it falls back to the default implementation, which is configured as tracking. 

We ccould solve this bug simply by adding @ProcessingGroup annotation to KafkaEventPublisher class, but I preferred to solve it in configuration without touching to the implementation.

**Comment by smcvb** [comment]
Aah darn, we actually noted this issue as something being amiss in the `EventProcessingConfigurer#assignHandlerTypesMatching(String, Predicate<Class<?>>)` implementation. This has been resolved in [this](e6249f13e71e70e71c187320bd7ecd1401ac8fbc) commit. This commit is part of Axon Framework release 4.4.3.

However, as you might have noticed, the Kafka Extension is on Axon Framework version 4.0.4 and as such is not taken this solution into account at all. We simply missed to provide an actual fix for this guy, for which I'd like to apologies.

This does mean your fix actually solves the problem for pre 4.4.3 version and thus definitely is a valuable addition.
I also agree on the angle you've taken with solving the problem by the way; just so you know.

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in PR #85
